name: Shared build workflow

on:
  workflow_call:

jobs:
  create-archive:
    name: "Creating archive"
    runs-on: "ubuntu-24.04"

    steps:
    - uses: actions/checkout@v4
      with:
        path: 'source'
        lfs: 'true'

    - uses: actions/upload-artifact@v4
      with:
        name: out-archive
        if-no-files-found: error
        path: |
          ${{github.workspace}}/source
          !${{github.workspace}}/source/README.md
          !${{github.workspace}}/source/LICENSE
